name: ci - build and push docker image to DockerHub

on:
  push:
    branches: production

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: guoweidocker/smart-personal-resume:latest
